color0 #293021
color1 #fd4663
color2 #aad97d
color3 #b8e4d7
color4 #89cdac
color5 #bfdea1
color6 #a3dccb
color7 #f2f3f2
color8 #656e5e
color9 #fd4663
color10 #aad97d
color11 #b8e4d7
color12 #89cdac
color13 #bfdea1
color14 #a3dccb
color15 #f2f3f2

cursor                #f2f3f2
cursor_text_color     #1f231a
background            #1f231a
foreground            #f2f3f2
selection_foreground  #b2b6af
selection_background  #293021
active_border_color   #aad97d
inactive_border_color #293021
url_color             #aad97d

active_tab_foreground   #1f221b
active_tab_background   #aad97d
inactive_tab_foreground #b2b6af
inactive_tab_background #293021
cursor_trail_color      #b2b6af
